### ISSUE TITLE
Nosetests start as multiprocess, but after a while only one is running

### ISSUE THREAD

**Issue by jfeldstein** [Ignas/nose_xunitmp#8]
https://stackoverflow.com/questions/38461515/nosetests-start-as-multiprocess-but-only-one-continues-to-run

I'm running

`nosetests -w tests/ --verbosity=3 --debug --debug-log=tests/logs/debug.log --xunitmp-file $CIRCLE_TEST_REPORTS/nose/junit.xml  --with-flaky --processes=4 --process-timeout=500 --process-restartworker`

And see all 4 tests start initially (selenium tests, so they launch instances of Chrome) but after most tests finish, all but one chrome instance close. 

After a few moments, only a single browser is running, and the tests continue in serial. 

What's going on?

**Comment by Ignas** [comment]
nose_xunitmp plugin only deals with reporting in mp environment this issue should be reported to nose bug tracker.
